version: "2"

services:
  kong-database:
    image: postgres:9.4
    container_name: kong-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - "db-data:/var/lib/postgresql/data"
  kong:
    image: kong:0.12.3-alpine
    container_name: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    restart: always
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 7946:7946
      - 7946:7946/udp
    links:
      - kong-database
    command: sh -c "kong prepare -p /usr/local/kong
             && kong migrations up
             && /usr/local/openresty/nginx/sbin/nginx -c /usr/local/kong/nginx.conf -p /usr/local/kong/"
  kong-dashboard:
    image: pgbi/kong-dashboard
    container_name: kong-dashboard
    ports:
      - "8080:8080"
    links:
      - kong
    command: start --kong-url http://kong:8001

volumes:
  db-data:
